### ISSUE TITLE
I redesigned the manual.

### ISSUE THREAD

**Issue by jeremymeyers** [hdavid/Grids#1]
Hey there-

As a random weekend COVID project, I redid the manual in a more graphical style, and made a bunch of edits to the content wording and organization to make it clearer (I think). I did reach out to @hdavid but didn't hear back so wanted to post it here. https://launchpad95manual.mystrikingly.com/  (i'm happy to make any adjustments or changes or anything)

**Comment by hdavid** [comment]
Hi Jeremy,

this project is grids, not LP95 :)

i will contact you via email.
